name: max_count
description: Flutter Realtime Game

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_native_splash: ^1.3.2
  auto_size_text: ^3.0.0
  firebase_database: ^9.0.5
  firebase_core: ^1.11.0
  just_audio: ^0.9.18
  internet_connection_checker: ^0.0.1+3
  provider: ^5.0.0
  rounded_loading_button: ^2.0.5
  shared_preferences: ^2.0.12
  audio_session: ^0.1.6+1
  audio_service: ^0.18.1
  just_audio_platform_interface: ^4.0.0
  google_mobile_ads: ^1.0.1
  nice_intro: ^0.1.4
  flutter_styled_toast: ^2.0.0
  firebase_app_check: ^0.0.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#5ED466"
  adaptive_icon_foreground: "assets/launcher_icon/foreground.png"

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/sounds/


  fonts:
    - family: PixelTitle
      fonts:
        - asset: fonts/pixelTitle.ttf
          style: italic

